spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

grpc:
  server:
    port: 0 # gRPC Server Random port

server:
  port: 8002 # 0 Web Server Random port
