server:
  port: 18762

spring:
  application:
    name: eureka-server2

eureka:
  instance:
    hostname: eureka2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka-node01:18761/eureka/
      defaultZone: http://eureka2:18761/eureka/,http://eureka3:18763/eureka/
