spring:
  # datasource ???????
  datasource:
    url: jdbc:mysql://localhost:3306/SpringCloud-Labs?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  # JPA ??????? JpaProperties ?
  jpa:
    show-sql: true # ?? SQL ??????????
    # Hibernate ??????? HibernateProperties ?
    hibernate:
      ddl-auto: none
