nacos:
  config:
    server-addr: 127.0.0.1:8848
    bootstrap:
      enable: true # 是否开启 Nacos 配置预加载功能。默认为 false。
      log-enable: true # 是否开启 Nacos 支持日志级别的加载时机。默认为 false。
    data-id: example
    type: PROPERTIES # 默认为 PROPERTIES。
    group: DEFAULT_GROUP # 默认为 DEFAULT_GROUP。
    namespace: # 默认为 null。

server:
  port: 8006

#TBC 2025-05-25 for testing