spring:
  application:
    name: user-service # 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8850
        cluster-name: SZ

grpc:
  # gRPC 服务器配置，对应 GrpcServerProperties 配置类
  server:
    port: 0 # gRPC Server 随机端口

server:
  port: 8002 # 0 Web Server 随机端口
