server:
  port: 8411
spring:
  application:
    name: consul-producer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: service-producer1	# 注册到consul的服务名称